nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: This is the BileMo API documentation
            version: 1.0.0
        paths: # Placer 'paths' sous 'documentation'
            '/api/login_check':
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
            '/api/client/{client_id}/user/{user_email}':
                get:
                    operationId: getClientUser
                    tags:
                        - Users
                    summary: Retrieves a user linked to a client
                    parameters:
                        -
                            name: client_id
                            in: path
                            description: 'Add unique client identifier'
                            required: true
                            schema:
                                type: integer
                            examples:
                                int:
                                    summary: '1'
                                    value: 1
                        -
                            name: user_email
                            in: path
                            description: 'Add the user email'
                            required: true
                            schema:
                                type: string
                            examples:
                                string:
                                    summary: 'user@BileMo.com'
                                    value: 'user@BileMo.com'
                    responses:
                        '200':
                            description: | 
                                Retrieves a user linked to a client
                                - If user has Admin role, return the example 
                                Value Schema
                                - If user has User role, return the example 
                                Value Schema without "delete" object
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Admin_User_Schema'
                delete:
                    operationId: deleteClientUser
                    tags:
                        - Users
                    summary: deletes a user (user with admin role only)
                    parameters:
                        - name: client_id
                          in: path
                          description: 'Add unique client identifier'
                          required: true
                          schema:
                              type: integer
                          examples:
                              int:
                                  summary: '1'
                                  value: 1
                        - name: user_email
                          in: path
                          description: 'Add the user email'
                          required: true
                          schema:
                              type: string
                          examples:
                              string:
                                  summary: 'user@BileMo.com'
                                  value: 'user@BileMo.com'
                    responses:
                        '204':
                            description: |
                                Delete a user linked to a client
                                - authorized only for users with administrator role
                                - returns only status 204
            '/api/client/{id}/users':
                get:
                    tags:
                        - Users
                    summary: Retrieves users linked to a client
                    operationId: getAllClientUsers
                    parameters:
                        -
                            name: id
                            in: path
                            description: 'Add unique client identifier'
                            required: true
                            schema:
                                type: integer
                            examples:
                                int:
                                    summary: '1'
                                    value: 1
                    responses:
                          200:
                              description: | 
                                Retrieves users linked to a client
                                - If user has Admin role, return the example 
                                Value Schema
                                - If user has User role, return the example 
                                Value Schema without "delete" object
                              content:
                                  application/json:
                                      schema:
                                          $ref: '#/components/schemas/Admin_User_Schema'
            '/api/client/user':
                post:
                    tags:
                        - Users
                    summary: add a new user linked to a customer
                    operationId: newClientUser
                    requestBody:
                        description: create a new user
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/New_User'
                    responses:
                        '200':
                            description: | 
                                Returns the new user
                                - If user has Admin role, return the example 
                                Value Schema
                                - If user has User role, return the example 
                                Value Schema without "delete" object
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Admin_User_Schema'
            '/api/mobiles':
                get:
                    tags:
                        - Mobiles
                    summary: Retrieves all mobiles
                    operationId: getMobilesList
                    responses:
                        '200':
                            description: |
                                Returns all mobiles
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Mobiles'
            '/api/mobile/{id}':
                get:
                    tags:
                        - Mobiles
                    summary: Retrieve one mobile
                    operationId: getMobile
                    parameters:
                        -
                            name: id
                            in: path
                            description: 'Add unique mobile identifier'
                            required: true
                            schema:
                                type: integer
                            examples:
                                int:
                                    summary: '1'
                                    value: 1
                    responses:
                        '200':
                            description: |
                                Returns one mobile
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Mobiles'
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: admin@BileMo.com
                        password:
                            type: string
                            default: password
                Admin_User_Schema:
                    type: object
                    properties:
                        id:
                            type: integer
                        email:
                            type: string
                        roles:
                            type: array
                            items: string
                        created_at:
                            type: string
                        client:
                            type: object
                            properties:
                                id: integer
                                name: string
                                created_at: string
                        _links:
                            type: object
                            properties:
                                self:
                                    type: object
                                    properties:
                                        href: string
                                delete:
                                    type: object
                                    properties:
                                        href: string
                New_User:
                    type: object
                    properties:
                        email:
                            type: string
                        password:
                            type: string
                        roles:
                            type: array
                            items: string
                        client:
                            type: object
                            properties:
                                id: integer
                Mobiles:
                    type: object
                    properties:
                        id:
                            type: integer
                        name:
                            type: string
                        description:
                            type: string
                        quantity:
                            type: integer
                        created_at:
                            type: string
                        brand:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                                created_at:
                                    type: string
                        _links:
                            type: object
                            properties:
                                self:
                                    type: object
                                    properties:
                                        href:
                                            type: string
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
